# .streamlit/secrets.toml
# 这里填每个人自己电脑上的真实配置

[mysql]
host = "localhost"
port = 3306
database = "大作业-test4"
username = "root"
password = "Lxl123756"  # <--- 每个人只需改这里
charset = "utf8mb4"

# 还可以放一些全局配置
[app]
debug = true